name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write  # to create releases
  pull-requests: write # to update the Homebrew tap

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          distribution: goreleaser
          args: release --clean
        env:
          # Standard GitHub token for uploading release assets
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Personal access token with push access to matanyall/homebrew-tap
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
